# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
#   cypress: cypress-io/cypress@1
# jobs:
#   build-with-npm-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
#             - run: npm test
#             - run: npm run e2e
# build-e2e:
#   docker:
#     # the Docker image with Cypress dependencies
#     - image: cypress/base:8
#       environment:
#         ## this enables colors in the output
#         TERM: xterm
#   working_directory: ~/app
#   parallelism: 1
#   steps:
#     - checkout
#     - restore_cache:
#         keys:
#           - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
#           - v2-deps-{{ .Branch }}-
#           - v2-deps-
#     - run: npm install
#     - save_cache:
#         key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
#         paths:
#           - ~/.npm
#           - ~/.cache
#     - node/with-cache:
#         steps:
#           - run: npm run start:dev
#           - run: npm test
#           - run: npm run e2e

# workflows:
#   build-and-test:
#     jobs:
#       - build-with-npm-test
# - build-e2e

version: 2.1
orbs:
  react: thefrontside/react@0.2.0
  cypress: cypress-io/cypress@1.0.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn e2e-wait
  cypress-e2e:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-npm-deps-{{ .Branch }}-
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          when: always
          name: Run Cypress E2E
          command: npm run start:dev && cypress run --browser chrome
      - store_artifacts:
          path: cypress/reports
      - store_artifacts:
          path: cypress/videos

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - cypress-e2e
