version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1.19.3
jobs:
  build-with-npm-test-and-npm-e2e:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run e2e
workflows:
  build-and-test:
    jobs:
      - build-with-npm-test-and-npm-e2e
