version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js

      - run: yarn e2e

      - run: yarn build

      - run: ls
      - run: cd ..
      - run: ls
      - store_artifacts:
          path: /build
workflows:
  build:
    jobs:
      - build
      # - cypress/run:
      #     install-command: npm install
      #     executor: cypress/browsers-chrome69
      #     browser: chrome
      #     start: npm run start
      #     wait-on: 'http://localhost:3000'
