# Definitions of Jobs

# Initial-Setup: Installs dependencies and forwards them.
# - Executes Node Docker image
# - Installs dependencies
# - Saves cache
# - Persists workspace to be forwarded to following pipes.

# Unit-Testing: Runs Unit testing suite.
# - Executes Node Docker image
# - Attaches previous workspace (dependencies)
# - Runs testing suite with yarn test.

# E2E-Testing: Runs E2E testing suite.
# - Executes Node Docker image,
# - Attaches previous workspace (dependencies)
# - Restores cache so Cypress binaries are present to run.
# - Establish a command in which allows the react-scripts interactive terminal to run

# Build: Builds the project and forwards it to the Deploy pipe.
# - Executes Node Docker Image
# - Attaches previous workspace (dependencies)
# - Runs the provided build command
# - Persist it to the following workspace to be consumed

# Deploy:
# - Deploys the build

version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12.9.1-browsers
  aws-executor:
    docker:
      - image: cibuilds/aws:latest
jobs:
  Initial-setup:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/Cypress
          key: v4-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - .
            - cache

  Unit-Testing:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run: yarn test
  E2E-Testing:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - run:
          name: 'Running React Server for e2e'
          command: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js

      - run: yarn e2e
  Build:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  Deploy:
    executor: aws-executor
    environment:
      BUILD_DIR: ~/publish
    steps:
      - attach_workspace:
          at: .
      - run: apk update
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "dev" ]; then
              aws s3 sync $BUILD_DIR \
              s3://dev.fcdevelopment.net/ --delete
            fi
            if [ "${CIRCLE_BRANCH}" = "qa" ]; then
              aws s3 sync $BUILD_DIR \
              s3://qa.fcdevelopment.net/ --delete
            fi
            if [ "${CIRCLE_BRANCH}" = "staging" ]; then
              aws s3 sync $BUILD_DIR \
              s3://staging.fcdevelopment.net/ --delete
            fi
workflows:
  version: 2

  Build-Test-Deploy:
    jobs:
      - Initial-setup
      - Unit-Testing:
          requires:
            - Initial-setup
      - E2E-Testing:
          requires:
            - Initial-setup
      - Build:
          requires:
            - Unit-Testing
            - E2E-Testing
      - Deploy:
          requires:
            - Build
