# version: 2.1

# jobs:
#   build-and-test:
#     docker:
#       - image: circleci/node:12.9.1-browsers
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             # fallback to using the latest cache if no exact match is found
#             - v1-dependencies-

#       - run: yarn install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       - run: yarn test

#       - run:
#           name: 'Running React Server for e2e'
#           command: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js

#       - run: yarn e2e

#       - run: yarn build

#       - run: cd build
#       - run: ls

#       - store_artifacts:
#           path: build
# workflows:
#   build:
#     jobs:
#       - build-and-test

version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.9.1-browsers

jobs:
  flow:
    executor: my-executor
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output
      - run: ls
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ls

      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: /workspace
          # Must be relative path from root
          paths:
            - node_modules
      - run: ls

  downstream:
    executor: my-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /workplace/node_modules

      - run: |
          if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
      - checkout
      - run: ls
      - run: yarn test
  downstream2:
    executor: my-executor
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run: |
          if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
      - downstream2:
          requires:
            - flow
