version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run:
          name: 'Running React Server for e2e'
          command: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js

      - run: yarn e2e

      - run: yarn build

      - run: cd build
      - run: ls

      - store_artifacts:
          path: build
  test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - run: ls
      - run: yarn test
      - run: sed -i '/process.env.CI/,+7 d' node_modules/react-scripts/scripts/start.js
      - run: e2e
workflows:
  build:
    jobs:
      - build-and-test
      - test:
          requires:
            - build-and-test
