version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build-and-test-with-e2e:
    executor:
      name: node/default
    steps:
      -checkout
      -node/with-cache:
        steps:
          -run: npm install
          -run: npm e2e
workflows:
    build-and-test:
      jobs:
        - build-and-test
    build-and-test-with-e2e:
      jobs:
        - build-and-test-with-e2e